// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC8lhRqDrp0JDDkGbPavnxnqlU8FjVFJjg',
    appId: '1:721509425416:web:e9894cba4e5e6728830cbd',
    messagingSenderId: '721509425416',
    projectId: 'bazar-9fe34',
    authDomain: 'bazar-9fe34.firebaseapp.com',
    storageBucket: 'bazar-9fe34.appspot.com',
    measurementId: 'G-RSEMR4NV92',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCF1ja3eRu6hCMAptWFMtHf3PYxfxlClmI',
    appId: '1:721509425416:android:8cbdf24010884867830cbd',
    messagingSenderId: '721509425416',
    projectId: 'bazar-9fe34',
    storageBucket: 'bazar-9fe34.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCXvNTOgWQIKkaDkOj0jPbNXMZA4Zb8h9w',
    appId: '1:721509425416:ios:6a05733fa4d5e5e4830cbd',
    messagingSenderId: '721509425416',
    projectId: 'bazar-9fe34',
    storageBucket: 'bazar-9fe34.appspot.com',
    iosBundleId: 'com.example.bazarApp',
  );
}
